name: Actualizar Datos KPI
on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta cada medianoche
  workflow_dispatch: # Esto activa el botÃ³n para ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install axios csv-parse

      - name: Ejecutar procesador de datos
        run: node scripts/build.js

      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add site/data.json
          git commit -m "ðŸ”„ ActualizaciÃ³n automÃ¡tica de KPIs" || exit 0
          git push
